# Generated by Django 5.1.7 on 2025-03-30 18:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title when this page appears on listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text description used when this page appears on listings. It's also used if meta description is absent",
                        max_length=255,
                    ),
                ),
                (
                    "appear_in_search_results",
                    models.BooleanField(
                        default=True,
                        help_text="Make this page indexable by search engines.If unchecked this page will no longer be indexed by search engines.",
                    ),
                ),
                (
                    "hero_text",
                    models.CharField(
                        help_text="Keep it short and powerful", max_length=255
                    ),
                ),
                (
                    "hero_cta",
                    models.CharField(
                        help_text="Text to display on Call to Action",
                        max_length=255,
                        verbose_name="Hero CTA",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading_block", 2),
                            ("paragraph_block", 3),
                            ("image_block", 6),
                            ("gallery", 7),
                            ("block_quote", 10),
                            ("embed_block", 11),
                            ("faq", 16),
                            ("document", 17),
                            ("link", 24),
                            ("further_reading", 24),
                            ("nav_tab", 28),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select a header size"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 0), ("size", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "template": "blocks/paragraph_block.html",
                                },
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("attribution", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {"template": "blocks/gallery_block.html"},
                            ),
                            8: ("wagtail.blocks.TextBlock", (), {}),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "label": "e.g. Mary Berry",
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 8), ("attribute_name", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                                    "icon": "media",
                                    "template": "blocks/embed_block.html",
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Frequently asked questions"},
                            ),
                            13: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": True},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 0), ("answer", 13)]],
                                {},
                            ),
                            15: ("wagtail.blocks.ListBlock", (14,), {}),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 12), ("item", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"template": "blocks/document_block.html"},
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use page's listing title.",
                                    "required": False,
                                },
                            ),
                            19: ("wagtail.blocks.PageChooserBlock", (), {}),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 18), ("page", 19)]],
                                {},
                            ),
                            21: ("wagtail.blocks.CharBlock", (), {}),
                            22: ("wagtail.blocks.URLBlock", (), {}),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 21), ("link", 22)]],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.StreamBlock",
                                [[("internal_link", 20), ("external_link", 23)]],
                                {},
                            ),
                            25: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "required": True,
                                    "template": "blocks/paragraph_block.html",
                                },
                            ),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("content", 25)]],
                                {},
                            ),
                            27: ("wagtail.blocks.ListBlock", (26,), {}),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("item", 27)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "promotions",
                    wagtail.fields.StreamField(
                        [("promotions", 6)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Keep it to one word only",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            3: ("wagtail.blocks.PageChooserBlock", (), {}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("image", 2), ("page", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.ListBlock", (4,), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 0), ("item", 5)]],
                                {},
                            ),
                        },
                        verbose_name="Promotions Section",
                    ),
                ),
                (
                    "featured_section_1_title",
                    models.CharField(
                        blank=True,
                        help_text="Title to display above the promo copy",
                        max_length=255,
                    ),
                ),
                (
                    "featured_section_2_title",
                    models.CharField(
                        blank=True,
                        help_text="Title to display above the promo copy",
                        max_length=255,
                    ),
                ),
                (
                    "featured_section_3_title",
                    models.CharField(
                        blank=True,
                        help_text="Title to display above the promo copy",
                        max_length=255,
                    ),
                ),
                (
                    "featured_pages",
                    wagtail.fields.StreamField(
                        [("featured", 6)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Keep it to one word only",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            3: ("wagtail.blocks.PageChooserBlock", (), {}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("image", 2), ("page", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.ListBlock", (4,), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 0), ("item", 5)]],
                                {},
                            ),
                        },
                        verbose_name="Popular Destinations Section",
                    ),
                ),
                (
                    "faq",
                    wagtail.fields.StreamField(
                        [("faq", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Frequently asked questions"},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            2: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 1), ("answer", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("item", 4)]],
                                {},
                            ),
                        },
                        verbose_name="FAQ Section",
                    ),
                ),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("Links", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use page's listing title.",
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.PageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("page", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 0), ("item", 4)]],
                                {},
                            ),
                        },
                        verbose_name="Links Section",
                    ),
                ),
                (
                    "featured_section_1",
                    models.ForeignKey(
                        blank=True,
                        help_text="First featured section for the homepage. Will display up to three child items.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Featured section 1",
                    ),
                ),
                (
                    "featured_section_2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Second featured section for the homepage. Will display up to three child items.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Featured section 2",
                    ),
                ),
                (
                    "featured_section_3",
                    models.ForeignKey(
                        blank=True,
                        help_text="Third featured section for the homepage. Will display up to six child items.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Featured section 3",
                    ),
                ),
                (
                    "hero_cta_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose a page to link to for the Call to Action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Hero CTA link",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Homepage image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose an image you wish to be displayed when this page appears on listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose an image you wish to display when this page appears on social media",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage",
                "verbose_name_plural": "homepages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
