# Generated by Django 4.1.3 on 2022-12-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name_plural": "homepage"},
        ),
    ]
