# Generated by Django 4.1.3 on 2022-12-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_homepage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "homepage"},
        ),
    ]
