# Generated by Django 4.2.3 on 2023-07-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_homepage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallToAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("html", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Calls To Actions",
            },
        ),
    ]
