# Generated by Django 5.1.2 on 2024-10-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "homepage", "verbose_name_plural": "homepages"},
        ),
    ]
