# Generated by Django 4.2.3 on 2023-07-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_calltoaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calltoaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
