# Generated by Django 5.1.2 on 2024-10-20 16:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_homepage_appear_in_search_results_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_block", 2),
                    ("paragraph_block", 3),
                    ("image_block", 6),
                    ("gallery", 7),
                    ("block_quote", 10),
                    ("embed_block", 11),
                    ("faq", 15),
                    ("document", 16),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "pilcrow", "template": "blocks/paragraph_block.html"},
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("attribution", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (6,),
                        {"template": "blocks/gallery_block.html"},
                    ),
                    8: ("wagtail.blocks.TextBlock", (), {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "label": "e.g. Mary Berry", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 8), ("attribute_name", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            "icon": "media",
                            "template": "blocks/embed_block.html",
                        },
                    ),
                    12: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("answer", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.ListBlock", (13,), {}),
                    15: ("wagtail.blocks.StructBlock", [[("item", 14)]], {}),
                    16: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"template": "blocks/document_block.html"},
                    ),
                },
            ),
        ),
    ]
