# Generated by Django 5.1.2 on 2024-12-05 23:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="faq",
            field=wagtail.fields.StreamField(
                [("faq", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently asked questions"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 1), ("answer", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("item", 4)]],
                        {},
                    ),
                },
                verbose_name="FAQ Section",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_pages",
            field=wagtail.fields.StreamField(
                [("featured", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Keep it to one word only", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("image", 2), ("page", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("item", 5)]],
                        {},
                    ),
                },
                verbose_name="Popular Destinations Section",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="links",
            field=wagtail.fields.StreamField(
                [("Links", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.PageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("page", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("item", 4)]],
                        {},
                    ),
                },
                verbose_name="Links Section",
            ),
        ),
    ]
