# Generated by Django 5.1.2 on 2024-12-06 18:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_homepage_faq_homepage_featured_pages_homepage_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="promo_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="promo_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="promo_title",
        ),
        migrations.AddField(
            model_name="homepage",
            name="promotions",
            field=wagtail.fields.StreamField(
                [("promotions", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Keep it to one word only", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("image", 2), ("page", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("item", 5)]],
                        {},
                    ),
                },
                verbose_name="Promotions Section",
            ),
        ),
    ]
