# Generated by Django 4.2.5 on 2023-09-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_formpage_body_alter_standardpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Countries of Origin",
            },
        ),
    ]
