# Generated by Django 4.2.4 on 2023-08-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("base", "0006_alter_formpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="uploaded_image_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailcore.collection",
            ),
        ),
    ]
