# Generated by Django 4.2.5 on 2023-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericsettings",
            name="youtube_url",
            field=models.URLField(blank=True, verbose_name="Youtube URL"),
        ),
    ]
