# Generated by Django 5.0.4 on 2024-05-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_genericsettings_youtube_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="title_suffix",
            field=models.CharField(
                default="Book Bus tickets",
                help_text="The suffix for the title meta tag e.g. ' | The Blog'",
                max_length=255,
                verbose_name="Title suffix",
            ),
        ),
    ]
