# Generated by Django 5.0.8 on 2024-09-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_formpage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footertext",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="title_suffix",
            field=models.CharField(
                default="Book Bus tickets",
                help_text="The suffix for the title meta tag e.g. ' | Blog'",
                max_length=255,
                verbose_name="Title suffix",
            ),
        ),
    ]
