# Generated by Django 4.2.4 on 2023-08-29 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_alter_formpage_body_alter_standardpage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formpage",
            options={"verbose_name": "formpage"},
        ),
        migrations.AlterModelOptions(
            name="standardpage",
            options={"verbose_name": "standardpage"},
        ),
    ]
