# Generated by Django 5.1.2 on 2024-12-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_genericimportantpages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genericimportantpages",
            options={"verbose_name": "Important pages"},
        ),
    ]
