# Generated by Django 5.2.1 on 2025-07-24 19:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_departure",
                    models.TimeField(null=True, verbose_name="First departure"),
                ),
                (
                    "last_departure",
                    models.TimeField(null=True, verbose_name="Last departure"),
                ),
                ("duration", models.DurationField(null=True, verbose_name="Duration")),
                (
                    "price_economy",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Price Economy",
                    ),
                ),
                (
                    "price_avg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Price Average",
                    ),
                ),
                (
                    "num_departures",
                    models.PositiveIntegerField(
                        null=True, verbose_name="Number of departures per day"
                    ),
                ),
                (
                    "companies",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="companies"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="trips.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="trips.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "stats",
                "verbose_name_plural": "stats",
                "indexes": [
                    models.Index(
                        fields=["-created_on"], name="trips_stats_created_20fc9e_idx"
                    )
                ],
            },
        ),
    ]
