# Generated by Django 6.0.2 on 2026-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='location',
            name='abbr',
            field=models.CharField(max_length=7, unique=True, verbose_name='abbr'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('BOL', 'Bolivia'), ('BRA', 'Brasil'), ('CHL', 'Chile'), ('PGY', 'Paraguay'), ('PER', 'Perú'), ('URU', 'Uruguay')], default='ARG', max_length=5, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('BUE', 'Buenos Aires'), ('CAT', 'Catamarca'), ('CHA', 'Chaco'), ('CHU', 'Chubut'), ('COR', 'Córdoba'), ('CRR', 'Corrientes'), ('ENT', 'Entre Ríos'), ('FOR', 'Formosa'), ('JUY', 'Jujuy'), ('LAP', 'La Pampa'), ('LAR', 'La Rioja'), ('MZA', 'Mendoza'), ('MIS', 'Misiones'), ('NEQ', 'Neuquén'), ('RNG', 'Río Negro'), ('SAL', 'Salta'), ('SJU', 'San Juan'), ('SLU', 'San Luis'), ('SCR', 'Santa Cruz'), ('SFE', 'Santa Fe'), ('SDE', 'Santiago Del Estero'), ('TDF', 'Tierra Del Fuego'), ('TUC', 'Tucumán')], max_length=5, verbose_name='Province'),
        ),
    ]
