# Generated by Django 5.2.1 on 2025-06-17 16:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_partnerpage_destinations_partnerpage_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerpage",
            name="ratings",
            field=wagtail.fields.StreamField(
                [("Ratings", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 5 stars?"},
                    ),
                    1: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 4 stars?"},
                    ),
                    2: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 3 stars?"},
                    ),
                    3: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 2 stars?"},
                    ),
                    4: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 1 star?"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("five", 0),
                                ("four", 1),
                                ("three", 2),
                                ("two", 3),
                                ("one", 4),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Ratings",
            ),
        ),
        migrations.AlterField(
            model_name="partnerpage",
            name="contact",
            field=wagtail.fields.StreamField(
                [("contact", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    2: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("phone", 0),
                                ("whatsapp", 0),
                                ("email", 1),
                                ("address", 2),
                                ("website", 3),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Contact Information",
            ),
        ),
    ]
