# Generated by Django 4.2.4 on 2023-08-31 22:31

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0002_partnerindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerpage",
            name="faq",
            field=wagtail.fields.StreamField(
                [
                    (
                        "faq",
                        wagtail.blocks.StructBlock(
                            [
                                ("question", wagtail.blocks.CharBlock(required=True)),
                                ("answer", wagtail.blocks.TextBlock(required=True)),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="FAQ Section",
            ),
        ),
        migrations.AlterField(
            model_name="partnerpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.blocks.CharBlock(required=True),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select a header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            icon="pilcrow", template="blocks/paragraph_block.html"
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "gallery",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "image",
                                        wagtail.images.blocks.ImageChooserBlock(
                                            required=True
                                        ),
                                    ),
                                    (
                                        "caption",
                                        wagtail.blocks.CharBlock(required=False),
                                    ),
                                    (
                                        "attribution",
                                        wagtail.blocks.CharBlock(required=False),
                                    ),
                                ]
                            ),
                            template="blocks/gallery_block.html",
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="e.g. Mary Berry",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            icon="media",
                            template="blocks/embed_block.html",
                        ),
                    ),
                    (
                        "faq",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "question",
                                        wagtail.blocks.CharBlock(required=True),
                                    ),
                                    ("answer", wagtail.blocks.TextBlock(required=True)),
                                ]
                            ),
                            template="blocks/faq_block.html",
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Page body",
            ),
        ),
    ]
