# Generated by Django 6.0.2 on 2026-05-02 07:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0003_partnerpage_ratings_alter_partnerpage_contact"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenity",
            name="icon",
        ),
        migrations.AddField(
            model_name="partnerpage",
            name="cities",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Cities"
            ),
        ),
        migrations.AddField(
            model_name="partnerpage",
            name="countries",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Countries"
            ),
        ),
        migrations.AddField(
            model_name="partnerpage",
            name="daily_departures",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Daily departures"
            ),
        ),
        migrations.AddField(
            model_name="partnerpage",
            name="num_routes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Routes"
            ),
        ),
        migrations.CreateModel(
            name="PartnerPageGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("caption", models.CharField(blank=True, max_length=250)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="partners.partnerpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "partnerpagegallery",
                "verbose_name_plural": "partnerpagegallery",
            },
        ),
    ]
