# Generated by Django 4.2.4 on 2023-09-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("partners", "0004_alter_partnerpage_body_alter_partnerpage_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
