# Generated by Django 4.2.5 on 2023-09-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0007_alter_partnerpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="icon_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the bootstrap icon",
                max_length=20,
                null=True,
            ),
        ),
    ]
