# Generated by Django 5.1.2 on 2024-11-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0010_partnerindexpage_appear_in_search_results_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerpage",
            name="intro",
            field=models.TextField(
                blank=True, help_text="A brief introduction about the company"
            ),
        ),
    ]
