# Generated by Django 5.2.1 on 2025-05-20 14:56

import django.core.validators
import django_countries.fields
import orders.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("PASSPORT", "PASSPORT"),
                            ("CE", "CEDULA"),
                            ("LE", "LE"),
                            ("LC", "LC"),
                            ("CUIT", "CUIT"),
                            ("NIE", "NIE"),
                            ("RG", "RG"),
                            ("RNE", "RNE"),
                            ("CPF", "CPF"),
                            ("RUT", "RUT"),
                            ("CURP", "CURP"),
                            ("CNPJ", "CNPJ"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nro de documento"
                    ),
                ),
                (
                    "nationality",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Nacionalidad"
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("last_name", models.CharField(max_length=50, verbose_name="Apellido")),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")],
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        validators=[orders.validators.validate_birth_date],
                        verbose_name="Fecha de nacimiento",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de teléfono debe tener el formato '+5491150251122'. Se permiten hasta 17 dígitos.",
                                regex="^\\+?1?\\d{9,17}$",
                            )
                        ],
                        verbose_name="Telefono",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "passenger",
                "verbose_name_plural": "passengers",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["-created_on"], name="orders_pass_created_b7ac92_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "email",
                    models.EmailField(
                        help_text="Enviaremos los pasajes a este email",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de teléfono debe tener el formato '+5491150251122'. Se permiten hasta 17 dígitos.",
                                regex="^\\+?1?\\d{9,17}$",
                            )
                        ],
                        verbose_name="Telefono",
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("payment_id", models.CharField(blank=True, max_length=250)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "passengers",
                    models.ManyToManyField(related_name="+", to="orders.passenger"),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["-created_on"], name="orders_orde_created_3fff13_idx"
                    )
                ],
            },
        ),
    ]
