# Generated by Django 5.2.1 on 2025-06-03 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                help_text="Ex: +5491150254321",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de teléfono debe tener el formato '+5491150251122'. Se permiten hasta 17 dígitos.",
                        regex="^\\+?1?\\d{9,17}$",
                    )
                ],
                verbose_name="Telefono",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("DNI", "DNI"),
                    ("PP", "PASSPORTE"),
                    ("CE", "CEDULA"),
                    ("LE", "LE"),
                    ("LC", "LC"),
                    ("CUIT", "CUIT"),
                    ("NIE", "NIE"),
                    ("RG", "RG"),
                    ("RNE", "RNE"),
                    ("CPF", "CPF"),
                    ("RUT", "RUT"),
                    ("CURP", "CURP"),
                    ("CNPJ", "CNPJ"),
                ],
                default="DNI",
                max_length=10,
                verbose_name="Tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")],
                default="F",
                max_length=1,
                verbose_name="Género",
            ),
        ),
    ]
