# Generated by Django 5.2.1 on 2025-07-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reservation_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
