# Generated by Django 6.0.2 on 2026-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagegalleryimage',
            options={'verbose_name': 'blogpagegallery', 'verbose_name_plural': 'blogpagegallery'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='icon',
            field=models.CharField(default='', help_text='Only name of the icon', max_length=20, verbose_name='icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
