# Generated by Django 4.2.4 on 2023-08-07 22:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            template="blog/blocks/image.html"
                        ),
                    ),
                    (
                        "gallery",
                        wagtail.blocks.ListBlock(
                            wagtail.images.blocks.ImageChooserBlock()
                        ),
                    ),
                    ("link", wagtail.blocks.URLBlock()),
                    (
                        "embed",
                        wagtail.embeds.blocks.EmbedBlock(
                            template="blog/blocks/embed.html"
                        ),
                    ),
                    ("email", wagtail.blocks.EmailBlock()),
                    ("datetime", wagtail.blocks.DateTimeBlock()),
                    ("date", wagtail.blocks.DateBlock()),
                    ("time", wagtail.blocks.TimeBlock()),
                    ("boolean", wagtail.blocks.BooleanBlock()),
                    ("html", wagtail.blocks.RawHTMLBlock()),
                    (
                        "blockquote",
                        wagtail.blocks.BlockQuoteBlock(
                            template="blog/blocks/blockquote.html"
                        ),
                    ),
                    (
                        "person",
                        wagtail.blocks.StructBlock(
                            [
                                ("first_name", wagtail.blocks.CharBlock()),
                                ("surname", wagtail.blocks.CharBlock()),
                                (
                                    "photo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                ("biography", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Post date"),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="feed_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Landscape mode only; horizontal width between 1000px to 3000px",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=models.CharField(max_length=255),
        ),
    ]
