# Generated by Django 4.2.4 on 2023-08-29 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_delete_blogtagindexpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "verbose_name": "blogcategory",
                "verbose_name_plural": "blog categories",
            },
        ),
        migrations.AlterModelOptions(
            name="blogpage",
            options={"verbose_name": "blogpage", "verbose_name_plural": "blogpages"},
        ),
        migrations.AlterModelOptions(
            name="blogpagegalleryimage",
            options={
                "verbose_name": "blogpagegallery",
                "verbose_name_plural": "blogpagegalleries",
            },
        ),
        migrations.AlterModelOptions(
            name="blogpagerelatedlink",
            options={
                "verbose_name": "blogpagerelatedlink",
                "verbose_name_plural": "blogpagerelatedlinks",
            },
        ),
        migrations.AlterModelOptions(
            name="blogpersonrelationship",
            options={"verbose_name": "blogpersonrelationship"},
        ),
    ]
