# Generated by Django 4.1.3 on 2022-12-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_landingpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogindexpage",
            options={"verbose_name": "blogindexpage"},
        ),
        migrations.AlterModelOptions(
            name="blogpage",
            options={"verbose_name": "blogpage"},
        ),
        migrations.AlterModelOptions(
            name="landingpage",
            options={"verbose_name": "landingpage"},
        ),
    ]
