# Generated by Django 4.2.3 on 2023-07-20 22:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_alter_docspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.TextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "gallery",
                        wagtail.blocks.ListBlock(
                            wagtail.images.blocks.ImageChooserBlock()
                        ),
                    ),
                    ("link", wagtail.blocks.URLBlock()),
                    ("email", wagtail.blocks.EmailBlock()),
                    ("datetime", wagtail.blocks.DateTimeBlock()),
                    ("date", wagtail.blocks.DateBlock()),
                    ("time", wagtail.blocks.TimeBlock()),
                    ("boolean", wagtail.blocks.BooleanBlock()),
                    ("html", wagtail.blocks.RawHTMLBlock()),
                    (
                        "blockquote",
                        wagtail.blocks.BlockQuoteBlock(form_classname="blockquote"),
                    ),
                    (
                        "person",
                        wagtail.blocks.StructBlock(
                            [
                                ("first_name", wagtail.blocks.CharBlock()),
                                ("surname", wagtail.blocks.CharBlock()),
                                (
                                    "photo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                ("biography", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
