# Generated by Django 4.2.3 on 2023-07-21 18:19

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_calltoaction_id"),
        ("blog", "0016_alter_docspage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="docspage",
            name="cta",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="home.calltoaction"
            ),
        ),
    ]
