# Generated by Django 4.2.5 on 2023-09-06 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0006_country"),
        ("wagtailcore", "0090_query_searchpromotion_querydailyhits"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station Page",
                "verbose_name_plural": "Station Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CityPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cities",
                        to="base.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "City Page",
                "verbose_name_plural": "City Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
