# Generated by Django 6.0.2 on 2026-03-05 09:44

import django.core.validators
import django.db.models.deletion
import locations.models
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('icon', models.CharField(help_text='Only name of the icon', max_length=20, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='stationpage',
            name='country',
            field=models.CharField(blank=True, choices=[('ARG', 'Argentina'), ('BOL', 'Bolivia'), ('BRA', 'Brasil'), ('CHL', 'Chile'), ('PGY', 'Paraguay'), ('PER', 'Perú'), ('URU', 'Uruguay')], max_length=20, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='directions',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('gallery', 7), ('block_quote', 10), ('embed_block', 11), ('faq', 16), ('document', 17), ('link', 24), ('further_reading', 24), ('nav_tab', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'template': 'blocks/gallery_block.html'}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('attribute_name', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'template': 'blocks/embed_block.html'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions'}), 13: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 14: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('item', 15)]], {}), 17: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'template': 'blocks/document_block.html'}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 19: ('wagtail.blocks.PageChooserBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('title', 18), ('page', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {}), 22: ('wagtail.blocks.URLBlock', (), {}), 23: ('wagtail.blocks.StructBlock', [[('title', 21), ('link', 22)]], {}), 24: ('wagtail.blocks.StreamBlock', [[('internal_link', 20), ('external_link', 23)]], {}), 25: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'required': True, 'template': 'blocks/paragraph_block.html'}), 26: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 27)]], {})}, verbose_name='Directions (Como llegar?)'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+5491150254191'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='province',
            field=models.CharField(blank=True, choices=[('BUE', 'Buenos Aires'), ('CAT', 'Catamarca'), ('CHA', 'Chaco'), ('CHU', 'Chubut'), ('COR', 'Córdoba'), ('CRR', 'Corrientes'), ('ENT', 'Entre Ríos'), ('FOR', 'Formosa'), ('JUY', 'Jujuy'), ('LAP', 'La Pampa'), ('LAR', 'La Rioja'), ('MZA', 'Mendoza'), ('MIS', 'Misiones'), ('NEQ', 'Neuquén'), ('RNG', 'Río Negro'), ('SAL', 'Salta'), ('SJU', 'San Juan'), ('SLU', 'San Luis'), ('SCR', 'Santa Cruz'), ('SFE', 'Santa Fe'), ('SDE', 'Santiago Del Estero'), ('TDF', 'Tierra Del Fuego'), ('TUC', 'Tucumán')], max_length=20, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='province_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminales', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='ratings',
            field=wagtail.fields.StreamField([('Ratings', 5)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 5 stars?'}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 4 stars?'}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 3 stars?'}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 2 stars?'}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 1 star?'}), 5: ('wagtail.blocks.StructBlock', [[('five', 0), ('four', 1), ('three', 2), ('two', 3), ('one', 4)]], {})}, verbose_name='Ratings'),
        ),
        migrations.AlterField(
            model_name='stationpage',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('weekday', models.PositiveIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('open_time', models.TimeField(default=locations.models.default_open_time, verbose_name='start')),
                ('close_time', models.TimeField(default=locations.models.default_close_time, verbose_name='end')),
                ('closed', models.BooleanField(default=False, verbose_name='closed')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='locations.stationpage')),
            ],
            options={
                'verbose_name': 'openinghour',
                'verbose_name_plural': 'openinghours',
            },
        ),
        migrations.AddField(
            model_name='stationpage',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='locations.service'),
        ),
        migrations.CreateModel(
            name='StationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title when this page appears on listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text description used when this page appears on listings. It's also used if meta description is absent", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page indexable by search engines.If unchecked this page will no longer be indexed by search engines.')),
                ('intro', models.TextField(blank=True, help_text='Text to describe the page')),
                ('body', wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('gallery', 7), ('block_quote', 10), ('embed_block', 11), ('faq', 16), ('document', 17), ('link', 24), ('further_reading', 24), ('nav_tab', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'template': 'blocks/gallery_block.html'}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('attribute_name', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'template': 'blocks/embed_block.html'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions'}), 13: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 14: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('item', 15)]], {}), 17: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'template': 'blocks/document_block.html'}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 19: ('wagtail.blocks.PageChooserBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('title', 18), ('page', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {}), 22: ('wagtail.blocks.URLBlock', (), {}), 23: ('wagtail.blocks.StructBlock', [[('title', 21), ('link', 22)]], {}), 24: ('wagtail.blocks.StreamBlock', [[('internal_link', 20), ('external_link', 23)]], {}), 25: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'required': True, 'template': 'blocks/paragraph_block.html'}), 26: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 27)]], {})}, verbose_name='Page body')),
                ('faq', wagtail.fields.StreamField([('faq', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions'}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 4)]], {})}, verbose_name='FAQ Section')),
                ('links', wagtail.fields.StreamField([('Links', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('page', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('item', 4)]], {})}, verbose_name='Links Section')),
                ('image', models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose an image you wish to be displayed when this page appears on listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('social_image', models.ForeignKey(blank=True, help_text='Choose an image you wish to display when this page appears on social media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Station Index Page',
                'verbose_name_plural': 'Station Index Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='StationPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='locations.stationpage')),
            ],
            options={
                'verbose_name': 'stationpagegallery',
                'verbose_name_plural': 'stationpagegallery',
            },
        ),
    ]
