# Generated by Django 5.1.2 on 2024-11-10 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_citypage_companies"),
    ]

    operations = [
        migrations.AddField(
            model_name="citypage",
            name="lat_long",
            field=models.CharField(
                blank=True,
                help_text="Comma separated lat/long. (Ex. 64.144367, -21.939182)                    Right click Google Maps and select 'What's Here'",
                max_length=36,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_lat_long",
                        message="Lat Long must be a comma-separated numeric lat and long",
                        regex="^(\\-?\\d+(\\.\\d+)?),\\s*(\\-?\\d+(\\.\\d+)?)$",
                    )
                ],
            ),
        ),
    ]
