# Generated by Django 5.1.2 on 2024-11-29 22:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_citypage_lat_long"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationpage",
            name="companies",
            field=wagtail.fields.StreamField(
                [("Links", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.PageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("page", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("item", 4)]],
                        {},
                    ),
                },
                verbose_name="Companies Section",
            ),
        ),
        migrations.AddField(
            model_name="stationpage",
            name="faq",
            field=wagtail.fields.StreamField(
                [("faq", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently asked questions"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 1), ("answer", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("item", 4)]],
                        {},
                    ),
                },
                verbose_name="FAQ Section",
            ),
        ),
        migrations.AddField(
            model_name="stationpage",
            name="links",
            field=wagtail.fields.StreamField(
                [("Links", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.PageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("page", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("item", 4)]],
                        {},
                    ),
                },
                verbose_name="Links Section",
            ),
        ),
    ]
